import type { Perfume } from '@/lib/types';

export const perfumes: Perfume[] = [
  {
    id: '1',
    number: 1,
    namaParfum: 'Midnight Bloom',
    deskripsiParfum: 'A captivating floral scent for evening wear, blending jasmine and tuberose with a warm, musky base. Perfect for special occasions.',
    topNotes: 'Jasmine, Gardenia',
    middleNotes: 'Tuberose, Ylang-Ylang',
    baseNotes: 'Musk, Sandalwood',
    penggunaan: 'Night',
    sex: 'Female',
    lokasi: 'Special Occasion',
    jenisAroma: 'Floral',
    kualitas: 'Eau de Parfum',
    imageUrl: 'https://picsum.photos/seed/1/400/600',
  },
  {
    id: '2',
    number: 2,
    namaParfum: 'Citrus Grove',
    deskripsiParfum: 'A refreshing and zesty citrus fragrance that evokes a sun-drenched grove. Ideal for daytime, casual wear.',
    topNotes: 'Bergamot, Lemon',
    middleNotes: 'Neroli, Orange Blossom',
    baseNotes: 'Vetiver, Cedarwood',
    penggunaan: 'Day',
    sex: 'Unisex',
    lokasi: 'Casual',
    jenisAroma: 'Citrus',
    kualitas: 'Eau de Toilette',
    imageUrl: 'https://picsum.photos/seed/2/400/600',
  },
  {
    id: '3',
    number: 3,
    namaParfum: 'Woodland Whisper',
    deskripsiParfum: 'An earthy and robust woody scent, reminiscent of a walk through a pine forest. A strong, masculine choice.',
    topNotes: 'Pine, Cypress',
    middleNotes: 'Cedarwood, Patchouli',
    baseNotes: 'Oakmoss, Amber',
    penggunaan: 'All Day',
    sex: 'Male',
    lokasi: 'Office',
    jenisAroma: 'Woody',
    kualitas: 'Eau de Parfum',
    imageUrl: 'https://picsum.photos/seed/3/400/600',
  },
  {
    id: '4',
    number: 4,
    namaParfum: 'Oceanic Drift',
    deskripsiParfum: 'A fresh aquatic fragrance that captures the essence of a cool sea breeze. Light, clean, and invigorating.',
    topNotes: 'Sea Salt, Ozonic Notes',
    middleNotes: 'Lavender, Sage',
    baseNotes: 'Driftwood, Ambergris',
    penggunaan: 'Day',
    sex: 'Unisex',
    lokasi: 'Beach',
    jenisAroma: 'Aquatic',
    kualitas: 'Eau de Cologne',
    imageUrl: 'https://picsum.photos/seed/4/400/600',
  },
];
